#@ load("@ytt:data", "data")
---
apiVersion: kapp.k14s.io/v1alpha1
kind: Config
rebaseRules:
#! git-ssh uses what's on the cluster
- paths:
  - [ data, identity ]
  - [ data, identity.pub ]
  - [ data, known_hosts ]
  - [ data, ssh-privatekey ]
  type: copy
  sources: [ existing, new ]
  resourceMatchers:
  - anyMatcher:
      matchers:
      #@ for user in data.values.users:
      - kindNamespaceNameMatcher:
          kind: Secret
          namespace: #@ user.name
          name: git-ssh
      #@ end
