apiVersion: v1
kind: Secret
metadata:
  name: grype-namespace
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: "tap-install-overlays"
type: Opaque
stringData:
  namespace.yml: |
    #@ load("@ytt:data", "data")
    ---
    apiVersion: v1
    kind: Namespace
    metadata:
      name: #@ data.values.namespace