tsunagu:
    token: ENC[AES256_GCM,data:D0PF4VExaFHafK8yN+WHRncRYZ3N/nOATdA72gTcXePANA1p,iv:679+cruVCOQQ+cOZIV+jfwur4eXV7T0qZixqV0h92IM=,tag:ncqENjfFUVB+0pI2Cm96xw==,type:str]
    remote: ENC[AES256_GCM,data:D8tvi/WnjwVL07uYNd9Ltmss7DoAFv6761R0FVlCw3DFit4ClXsRzZE2,iv:6aRintwSnKBOwftkOkG3ekafvG9AAeWCimplcAcquTE=,tag:7aEr6IZiXW77gk0wGEnjrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-05-17T05:14:29Z"
    mac: ENC[AES256_GCM,data:9MxgN+Cyqqv8Ei0ocJD/CzGgxXzXm4fjU5Hiw32ftj8RhHonZXz1i9ySEX94NF5h5SEb9nj1Dud5n4SO1x0rmvq2ZVKfwSxF/rMYARlEtZRYSlOXyIJEdZca93mfRJtaFvA2VeY+S0UvZsDLOz/4WDpmmjghS72AEXGJpfY7qnw=,iv:D+YfclVDLn7bVMLb8PYIE8FH6IULmjtY+TBhc0AvDTY=,tag:/uCs4A03opanG6qqCSQpJw==,type:str]
    pgp:
        - created_at: "2022-05-17T05:14:26Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAz83QxD1SKXbARAAl0xzIn60jgFSb0shTBK+99b80AwEd+H6BQwyYBfIL5Bo
            bKyvN/6Ovq3hVgt9HEX0IG6T6gheEOeev1Fpm3fyEWmZv2wukV/azYMJ3mu8XZ4/
            kzbwMja0yVN8GYxFW1M90oeoAfW76DlAeBMMlyrPL3Gqow02s0BHLQxUFD/iYIGu
            hrZv2jutTWwWQCD8glPK5l5k/xN7WPu3xTwQv1UsyZz9EqjsnL10GUbUYkSFFjz3
            XZizgfNSnAVMoodzo46cj+wTtectWPTtwcrQD4Oc38HUFpBiiyTfcKXknuASnK+O
            ro6YSwofPKwm21A4V3xmLx4hKytAQRYJl5eClkzte1sWn3DfO+O3ElaN1kfmVWV3
            /m2YvR+aTJkJK4FzZSVsuh5nggIS4QgCwxs8F9L+t+tAZmuzHCQwYXRxrBys1DDg
            BC1op2U+9UJrpqksoHcRhb7yCyCY+obogtILrA2Tsy5azNW12CzBH96kOpdyE2yH
            ZxxPJxznVr4HGhfwq0MFEAnHRdEA6MgwCKGfvuGqqHwL/Kl3zgX2o69uOx0JwdlV
            Oz83FenWcZwZ+bm10SIQg0U+3uvX+mIhgpKw0z1+kTKVFo7Q9C+R/2F/dJhTcthK
            otUIplCknd0q+XFwtkKQK7lNjG0LhMe11Rl2Tzc4a9YPh6R+rMjcuTz21WFx25rS
            XAHYCbAgVsyCoCUQhr542aCxU7RAvN7Y/FnNXPDhWAVyC6e8QFlQQsfhgzuOiFwd
            0QsX0QpWDMbQKZfjDNLBZoKuP++LDGAeC+7R9FtXWVmCV41mpbr0VDJVr2bs
            =KSC6
            -----END PGP MESSAGE-----
          fp: 1997AA2DBF0982F972B61D91D127B098EF01F86D
    unencrypted_suffix: _unencrypted
    version: 3.7.3
