apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.0: fluent-bit-elasticsearch-password
    kapp.k14s.io/change-group: "{name}"
    kapp.k14s.io/change-rule.create-order.0: "upsert after upserting fluent-bit-values"
    kapp.k14s.io/change-rule.delete-order.0: "delete before deleting fluent-bit-values"
    kapp.k14s.io/change-rule.create-order.1: "upsert after upserting fluent-bit-overlays"
    kapp.k14s.io/change-rule.delete-order.1: "delete before deleting fluent-bit-overlays"
  name: fluent-bit
  namespace: kapp
spec:
  packageRef:
    refName: fluent-bit.tanzu.vmware.com
    versionSelection:
      constraints: 1.7.5+vmware.2-tkg.1
      prereleases: { }
  serviceAccountName: kapp
  values:
  - secretRef:
      name: fluent-bit-values