apiVersion: v1
kind: Secret
metadata:
  name: buildservice-export-registry-credentials
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: "tap-install-overlays"
type: Opaque
stringData:
  registry-credentials.yaml: |
    #@ load("@ytt:data", "data")
    apiVersion: v1
    kind: Secret
    metadata:
      name: registry-credentials
      namespace: build-service
    type: kubernetes.io/dockerconfigjson
    stringData:
      #@yaml/text-templated-strings
      .dockerconfigjson: |-
        {
          "auths": {
            "(@= data.values.kp_default_repository.split("/")[0] @)": {
              "username": "(@= data.values.kp_default_repository_username @)",
              "password": "(@= data.values.kp_default_repository_password @)"
            }
          }
        }
  secret-export.yaml: |
    apiVersion: secretgen.carvel.dev/v1alpha1
    kind: SecretExport
    metadata:
      name: registry-credentials
      namespace: build-service
    spec:
      toNamespaces:
      - '*'