#@ load("@ytt:data", "data")
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-recursive-nameservers
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: "tap-install-overlays"
type: Opaque
stringData:
  #! https://cert-manager.io/docs/configuration/acme/dns01/#setting-nameservers-for-dns01-self-check
  #@yaml/text-templated-strings
  recursive-nameservers.yml: |
    #@ load("@ytt:overlay", "overlay")
    (@ if hasattr(data.values, "recursive_nameservers") and len(data.values.recursive_nameservers) > 0: @)
    #@overlay/match by=overlay.subset({"kind":"Deployment","metadata":{"name":"cert-manager"}})
    ---
    spec:
      template:
        spec:
          containers:
          #@overlay/match by="name"
          - name: cert-manager
            args:
            #@overlay/append
            - --dns01-recursive-nameservers-only
            #@overlay/append
            - --dns01-recursive-nameservers=(@= ",".join(data.values.recursive_nameservers) @)
    (@ end @)