apiVersion: v1
kind: Secret
metadata:
  name: learningcenter-certificate
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: "tap-install-overlays"
type: Opaque
stringData:
  certificate.yml: |
    #@ load("@ytt:data", "data")
    ---
    apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: learningcenter-tls
      namespace: #@ data.values.namespace
    spec:
      dnsNames:
      - #@ data.values.ingressDomain
      - #@ "*.{}".format(data.values.ingressDomain)    
      issuerRef:
        kind: ClusterIssuer
        name: letsencrypt
      secretName: learningcenter-tls