apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tanzu-data-services-repository
  namespace: tds-system
  annotations:
    kapp.k14s.io/change-rule.create-order: "upsert after upserting tds-system-namespace"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting tds-system-namespace"
spec:
  fetch:
    imgpkgBundle:
      image: ghcr.io/jaguchi/packages-for-vmware-tanzu-data-services/tds-packages:1.0.1
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tanzu-rabbitmq-repo
  namespace: tds-system
  annotations:
    kapp.k14s.io/change-rule.create-order: "upsert after upserting tds-system-namespace"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting tds-system-namespace"
spec:
  fetch:
    imgpkgBundle:
      image: registry.tanzu.vmware.com/p-rabbitmq-for-kubernetes/tanzu-rabbitmq-package-repo:1.2.0