apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: apps
  namespace: kapp
spec:
  serviceAccountName: kapp
  fetch:
  - git:
      url: git@github.com:tanzu-japan/jaguchi-manifests.git
      ref: origin/main
      subPath: jaguchi
      secretRef:
        name: github
  syncPeriod: 1m
  template:
  - ytt:
      paths:
      - kapp/platform
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true
      - --diff-mask=true
      inspect:
        rawOptions:
        - --tree=true
