apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: tanzu-rabbitmq-tds-system
    kapp.k14s.io/change-group: "tanzu-rabbitmq-rbac"
  name: tanzu-rabbitmq-tds-system-cluster-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: tanzu-rabbitmq-tds-system
    kapp.k14s.io/change-group: "tanzu-rabbitmq-rbac"
  name: tanzu-rabbitmq-tds-system-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tanzu-rabbitmq-tds-system-cluster-role
subjects:
- kind: ServiceAccount
  name: tanzu-rabbitmq-tds-system-sa
  namespace: tds-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: tanzu-rabbitmq-tds-system
    kapp.k14s.io/change-group: "tanzu-rabbitmq-rbac"
  name: tanzu-rabbitmq-tds-system-sa
  namespace: tds-system