apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: curator
  namespace: kapp
  annotations:
    kapp.k14s.io/change-group: "{name}"
    kapp.k14s.io/change-rule.create-order: "upsert after upserting elastic-cloud"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting elastic-cloud"
spec:
  serviceAccountName: kapp
  fetch:
  - git:
      url: https://github.com/tanzu-japan/jaguchi-manifests.git
      ref: origin/main
      subPath: jaguchi/config/platform/curator
  syncPeriod: 6h
  template:
  - ytt:
      paths:
      - "."
  - kbld:
      paths:
      - "-"
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true
      - --diff-mask=true
      - --app-changes-max-to-keep=3
      delete:
        #! Force delete PVCs, since StatefulSet does not delete them
        rawOptions:
        - --apply-ignored=true
      inspect:
        rawOptions:
        - --tree=true