apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: dex
  namespace: kapp
  annotations:
    kapp.k14s.io/change-group: "{name}"
    kapp.k14s.io/change-rule.create-order: "upsert after upserting tap-install"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting tap-install"
spec:
  serviceAccountName: kapp
  fetch:
  - helmChart:
      name: dex
      version: "0.8.2"
      repository:
        url: https://charts.dexidp.io
  - git:
      url: https://github.com/tanzu-japan/jaguchi-manifests.git
      ref: origin/main
  syncPeriod: 10m
  template:
  - sops:
      pgp:
        privateKeysSecretRef:
          name: pgp-key
  - ytt:
      ignoreUnknownComments: true
      paths:
      - 1/jaguchi/config/platform/dex/helm-values.yaml
      valuesFrom:
      - path: 1/common/credentials.yaml
      - path: 1/jaguchi/config/platform/tap-install/tap-data-values.yaml
  - helmTemplate:
      namespace: dex
      path: 0/
      valuesFrom:
      - path: "-"
  - ytt:
      ignoreUnknownComments: true
      paths:
      - "-"
      - 1/common/dex
      valuesFrom:
      - path: 1/jaguchi/config/platform/tap-install/tap-data-values.yaml
  - kbld:
      paths:
      - "-"
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true
      - --diff-mask=true
      - --app-changes-max-to-keep=3
      delete:
        #! Force delete PVCs, since StatefulSet does not delete them
        rawOptions:
        - --apply-ignored=true
      inspect:
        rawOptions:
        - --tree=true