apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: fluent-bit-install
  namespace: kapp
  annotations:
    kapp.k14s.io/change-group: "{name}"
    kapp.k14s.io/change-rule.create-order.0: "upsert after upserting tanzu-standard-repository-install"
    kapp.k14s.io/change-rule.delete-order.0: "delete before deleting tanzu-standard-repository-install"
    kapp.k14s.io/change-rule.create-order.1: "upsert after upserting elastic-cloud"
    kapp.k14s.io/change-rule.delete-order.1: "delete before deleting elastic-cloud"
spec:
  serviceAccountName: kapp
  fetch:
  - git:
      url: https://github.com/tanzu-japan/jaguchi-manifests.git
      ref: origin/main
      subPath: common/fluent-bit
  syncPeriod: 10m
  template:
  - ytt:
      paths:
      - '.'
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true
      - --diff-mask=true
      - --app-changes-max-to-keep=3
      delete:
        #! Force delete PVCs, since StatefulSet does not delete them
        rawOptions:
        - --apply-ignored=true
      inspect:
        rawOptions:
        - --tree=true