apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: tap-install
  namespace: kapp
  annotations:
    kapp.k14s.io/change-group: "{name}"
    kapp.k14s.io/change-rule.create-order: "upsert after upserting tap-repository"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting tap-repository"
spec:
  serviceAccountName: kapp
  fetch:
  - git:
      url: https://github.com/tanzu-japan/jaguchi-manifests.git
      ref: origin/main
  syncPeriod: 10m
  template:
  - sops:
      pgp:
        privateKeysSecretRef:
          name: pgp-key
  - ytt:
      paths:
      - jaguchi/config/platform/tap-install/tap-install-rbac.yaml
      # - jaguchi/config/platform/tap-install/tap-install-values.yaml
      # - jaguchi/config/platform/tap-install/tap-package-install.yaml
      - jaguchi/config/platform/tap-install/overlays
      valuesFrom:
      - path: common/credentials.yaml
      # - path: jaguchi/config/platform/tap-install-data-values.yaml
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true
      - --diff-mask=true
      inspect:
        rawOptions:
        - --tree=true