apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: tap-users
  namespace: kapp
  annotations:
    kapp.k14s.io/change-group: "{name}"
    kapp.k14s.io/change-rule.create-order: "upsert after upserting tap-install"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting tap-install"
spec:
  serviceAccountName: kapp
  fetch:
  - git:
      url: https://github.com/tanzu-japan/jaguchi-manifests.git
      ref: origin/main
  syncPeriod: 1m
  template:
  - ytt:
      paths:
      - common/tap-users
      valuesFrom:
      - path: jaguchi/config/platform/tap-users/tap-users-data-values.yaml
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true
      - --diff-mask=true
      inspect:
        rawOptions:
        - --tree=true