apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: tsunagu-client-install
  namespace: kapp
  annotations:
    kapp.k14s.io/change-group: "{name}"
    kapp.k14s.io/change-rule.create-order: "upsert after upserting tsunagu-repository-install"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting tsunagu-repository-install"
spec:
  serviceAccountName: kapp
  fetch:
  - git:
      url: https://github.com/tanzu-japan/jaguchi-manifests.git
      ref: origin/main
  syncPeriod: 10m
  template:
  - sops:
      pgp:
        privateKeysSecretRef:
          name: pgp-key
  - ytt:
      paths:
      - common/tsunagu-client
      - jaguchi/config/platform/tsunagu-client/tsunagu-client-values.yaml
      valuesFrom:
      - path: jaguchi/config/platform/tsunagu-client/credentials.yaml
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true
      - --diff-mask=true
      - --app-changes-max-to-keep=3
      delete:
        #! Force delete PVCs, since StatefulSet does not delete them
        rawOptions:
        - --apply-ignored=true
      inspect:
        rawOptions:
        - --tree=true